### ISSUE TITLE
delete($id) method masks parent delete() method

### ISSUE THREAD

**Issue by lfolco** [jetrails/magento-cloudflare#156]
I'm seeing an error in the logs about this method:

https://github.com/jetrails/magento-cloudflare/blob/master/src/app/code/community/JetRails/Cloudflare/Model/Adminhtml/Api/Firewall/AccessRules.php#L26

The `delete($id)` method has a different method signature than the one in `\Mage_Core_Model_Abstract::delete()`.

**Comment by null93** [comment]
Hello, thanks for taking the time to open a ticket about this! Can you paste the actual error you are seeing from the log file? I am not sure if it is necessary to keep the same signature as the base class for this module's use case. That being said, I am willing to change it for compatibility sake since the solution is really harmless.

Solution should be as easy as renaming the method to something other than `delete`. Something like `deleteEntry` should do. Effected classes:

- src/app/code/community/JetRails/Cloudflare/Model/Adminhtml/Api/Firewall/AccessRules.php
- src/app/code/community/JetRails/Cloudflare/Model/Adminhtml/Api/Firewall/ZoneLockdown.php
- src/app/code/community/JetRails/Cloudflare/Model/Adminhtml/Api/Firewall/UserAgentBlocking.php
- src/app/code/community/JetRails/Cloudflare/Model/Adminhtml/Api/PageRules/PageRules.php
